name: Go build and test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
